# Generated by Django 5.2.6 on 2025-09-25 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registrationsetting_participant_used_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AddField(
            model_name='participant',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='participant',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, verbose_name="Type d'événement"),
        ),
        migrations.AddField(
            model_name='participant',
            name='organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='participant',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ticket_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ticket UUID'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Utilisé'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le'),
        ),
    ]
