# Generated by Django 5.2.6 on 2025-09-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20250925_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Notre Événement', max_length=200, verbose_name="Nom de l'événement")),
                ('event_description', models.TextField(blank=True, verbose_name="Description de l'événement")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
