# Generated by Django 5.2.6 on 2025-09-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de début'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='venue',
            field=models.CharField(blank=True, max_length=300, verbose_name="Lieu de l'événement"),
        ),
    ]
