# Generated by Django 5.2.6 on 2025-09-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventsettings_end_date_eventsettings_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='event_logos/', verbose_name="Logo de l'événement"),
        ),
    ]
