# Generated by Django 5.2.8 on 2025-11-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventsettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, help_text='Email utilisé comme expéditeur', max_length=255, verbose_name='Email expéditeur'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='Ex: smtp.gmail.com', max_length=255, verbose_name='Serveur SMTP'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Mot de passe SMTP', max_length=255, verbose_name='Mot de passe SMTP'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='smtp_port',
            field=models.IntegerField(blank=True, help_text='Ex: 587 pour TLS, 465 pour SSL', null=True, verbose_name='Port SMTP'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Cocher pour SSL (port 465)', verbose_name='Utiliser SSL'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=False, help_text='Cocher pour TLS (port 587)', verbose_name='Utiliser TLS'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='smtp_user',
            field=models.CharField(blank=True, help_text="Email ou nom d'utilisateur", max_length=255, verbose_name='Utilisateur SMTP'),
        ),
    ]
